--- 
# Config
gateway: 192.168.1.3
lan_subnets:
  - 192.168.1.0/24 
  - 192.168.2.0/24
masquerade:
  - 192.168.1.0/24
  - 192.168.2.0/24
device: enp2s0
# DHCP options
broadcast-address: 192.168.1.25
dhcp-subnet: 192.168.1.0
dhcp-netmask: 255.255.255.0
dhcp-range: "192.168.1.100 192.168.1.200"

--- 
# Queue groups

kiel:
  desc: Kiel's devices
  priority: 1
  download_speed: 1gbit
  upload_speed: 1gbit
 
  # User level blocking.
  blocked: false

  devices:
  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Kiel's iPad
    hostname: kiels-ipad
    priority: 1
    mac: 5c:f7:e6:20:35:8d
    ip: 192.168.1.23
    dhcp: true

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Kiel's laptop WiFi
    hostname: kiels-laptop
    priority: 1
    mac: 3c:22:fb:86:e8:66
    ip: 192.168.1.6
    dhcp: true

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Kiel's laptop OLD WiFi
    hostname: kiels-laptop-old
    priority: 1
    mac: b8:e8:56:33:8c:30
    ip: 192.168.1.7
    dhcp: true

  - download_speed: 100mbps
    upload_speed: 100mbps

    desc: Kiel's laptop Wired
    hostname: kiels-laptop-wired
    priority: 1

    mac: 00:e0:4c:36:90:41
    ip: 192.168.1.96
    dhcp: true

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Kiel's phone2
    hostname: kiels-phone
    priority: 1
    mac: a8:3e:0e:9c:49:e7
    ip: 192.168.1.4
    dhcp: true
    blocking:
      # Device level blocking. Can be with or without a schedule.
      active: false
      schedule:
        monday: 
          unblock: 6:10
          block: 10:00
        tuesday: 
          unblock: 6:00
          block: 21:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 23:00
        friday: 
          unblock: 6:00
          block: 23:00
        saturday:
          unblock: 6:00
          block: 22:00
        sunday:
          unblock: 6:00
          block: 22:00

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Kiel's phone
    hostname: kiels-phone2
    priority: 1
    mac: f8:a9:d0:4d:ab:63
    ip: 192.168.1.5
    dhcp: true
    
  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Garage laptop
    hostname: garage-laptop
    priority: 1
    mac: 00:26:5e:82:c5:21
    ip: 192.168.1.70
    dhcp: true

sarah:
  desc: Sarah's devices
  priority: 2
  download_speed: 1gbit
  upload_speed: 1gbit

  devices:
  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Sarah's phone
    hostname: sarahs-phone
    priority: 2
    mac: a8:3e:0e:9c:49:68
    ip: 192.168.1.53
    dhcp: true

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Sarah's laptop
    hostname: sarahs-laptop
    priority: 2
    #mac: 64:80:99:FB:56:44
    mac: c8:58:c0:ab:91:e5
    ip: 192.168.1.51
    dhcp: true
    blocking:
      # Device level blocking. Can be with or without a schedule.
      active: false
    
eliza:
  desc: Eliza's devices
  priority: 3
  download_speed: 54mbps
  upload_speed: 54mbps
  blocked: false

  devices:
  
  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Eliza's iPad
    hostname: elizas-ipad
    priority: 3
    mac: 24:a0:74:1a:95:23
    ip: 192.168.1.41
    dhcp: true

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Eliza's Phone
    hostname: elizas-phone
    priority: 3
    #mac: 38:f8:89:ec:5a:06
    #mac: 58:1F:AA:87:69:99
    mac: d4:1a:3f:e6:82:c1
    ip: 192.168.1.42
    dhcp: true

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Eliza's tablet
    hostname: elizas-tablet
    priority: 3
    mac: 14:dd:a9:46:bf:e4
    ip: 192.168.1.40
    dhcp: true

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Eliza's Laptop
    hostname: elizas-laptop
    priority: 3
    # old 
    #mac: c4:3a:35:90:5e:30
    mac: 2c:f0:ee:2f:6f:ba
    ip: 192.168.1.43
    dhcp: true

evie:
  desc: Evie's devices
  priority: 3
  download_speed: 54mbps
  upload_speed: 54mbps
  blocked: false

  devices:
  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Evie's laptop
    hostname: evies-laptop
    priority: 3
    #mac: c4:3a:35:90:5e:3f
    mac: 2c:f0:ee:29:25:28
    ip: 192.168.1.20
    dhcp: true
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Evie's tablet
    hostname: evies-tablet
    priority: 3
    mac: 14:dd:a9:46:b7:80
    ip: 192.168.1.21
    dhcp: true
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Evie's phone
    hostname: evies-phone
    priority: 3
    mac: a0:28:ed:dd:01:fc
    ip: 192.168.1.24
    dhcp: true
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

isac:
  desc: Isac's devices
  priority: 3
  download_speed: 54mbps
  upload_speed: 54mbps
  blocked: false
  devices:
  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Isac's Wii
    hostname: isacs-wii
    priority: 3
    mac: 00:19:fd:07:2d:4f
    ip: 192.168.1.17
    dhcp: true
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 23:30
        tuesday: 
          unblock: 6:00
          block: 23:30
        wednesday: 
          unblock: 6:00
          block: 23:30
        thursday: 
          unblock: 6:00
          block: 23:30
        friday:
          block: 23:30
          unblock: 6:00
        sunday:
          block: 23:30
          unblock: 6:00

  - download_speed: 5mbps
    upload_speed: 2mbps
    desc: Isac's Desktop
    hostname: isacs-desktop
    priority: 3
    mac: a8:a1:59:19:18:33
    #mac: 80:32:53:90:d9:31

    ip: 192.168.1.16
    dhcp: true
    domain-name-servers: 
      - 192.168.1.3
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 23:30
        tuesday: 
          unblock: 6:00
          block: 23:30
        wednesday: 
          unblock: 6:00
          block: 23:30
        thursday: 
          unblock: 6:00
          block: 23:30
        friday:
          block: 23:30
          unblock: 6:00
        sunday:
          block: 23:30
          unblock: 6:00

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Isac's Google Home Mini
    hostname: isacs-google-home-mini
    priority: 3
    mac: 20:df:b9:a6:52:55
    ip: 192.168.1.8
    dhcp: true
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 23:30
        tuesday: 
          unblock: 6:00
          block: 23:30
        wednesday: 
          unblock: 6:00
          block: 23:30
        thursday: 
          unblock: 6:00
          block: 23:30
        friday:
          block: 23:30
          unblock: 6:00
        sunday:
          block: 23:30
          unblock: 6:00

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Isac's Chromecast
    hostname: isacs-chromecast
    priority: 3
    mac: 7c:d9:5c:5b:f0:aa
    ip: 192.168.1.12
    dhcp: true
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 23:30
        tuesday: 
          unblock: 6:00
          block: 23:30
        wednesday: 
          unblock: 6:00
          block: 23:30
        thursday: 
          unblock: 6:00
          block: 23:30
        friday:
          block: 23:30
          unblock: 6:00
        sunday:
          block: 23:30
          unblock: 6:00

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Isac's phone
    hostname: isacs-phone
    priority: 3
    mac: 76:2f:71:93:03:bc
    ip: 192.168.1.9
    dhcp: true
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 23:30
        tuesday: 
          unblock: 6:00
          block: 23:30
        wednesday: 
          unblock: 6:00
          block: 23:30
        thursday: 
          unblock: 6:00
          block: 23:30
        friday:
          block: 23:30
          unblock: 6:00
        sunday:
          block: 23:30
          unblock: 6:00

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Isac's computer
    hostname: isacs-computer
    priority: 3
    mac: 28:3a:4d:0f:c3:c3
    ip: 192.168.1.14
    dhcp: true
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 23:30
        tuesday: 
          unblock: 6:00
          block: 23:30
        wednesday: 
          unblock: 6:00
          block: 23:30
        thursday: 
          unblock: 6:00
          block: 23:30
        friday:
          block: 23:30
          unblock: 6:00
        sunday:
          block: 23:30
          unblock: 6:00

  - download_speed: 2mbps
    upload_speed: 2mbps
    desc: Isac's computer 2
    hostname: isacs-computer2
    priority: 3
    #mac: 38:b1:db:90:73:89
    mac: a6:5f:65:b8:9e:f7
    ip: 192.168.1.15
    dhcp: true
    blocking:
      active: false
      schedule:
        monday: 
          unblock: 6:00
          block: 23:30
        tuesday: 
          unblock: 6:00
          block: 23:30
        wednesday: 
          unblock: 6:00
          block: 23:30
        thursday: 
          unblock: 6:00
          block: 23:30
        friday:
          block: 23:30
          unblock: 6:00
        sunday:
          block: 23:30
          unblock: 6:00

linda:
  desc: Linda's devices
  priority: 3
  download_speed: 1000mbit
  upload_speed: 1000mbit

  devices:
  - download_speed: 100mbit
    desc: Linda's iPad
    hostname: lindas-ipad
    priority: 3
    upload_speed: 100mbit
    mac: b8:63:4d:cc:e8:1a
    ip: 192.168.1.60
    dhcp: true

  - download_speed: 100mbit
    desc: Linda's Phone
    hostname: lindas-phone
    priority: 3
    upload_speed: 100mbit
    mac: d8:c4:6a:cb:53:ca
    ip: 192.168.1.61
    dhcp: true

media:
  desc: Media devices
  priority: 1
  download_speed: 1gbit
  upload_speed: 1gbit

  devices:
  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Samsung
    hostname: camera
    priority: 1
    mac: a0:21:95:5c:2b:7e
    ip: 192.168.1.98
    dhcp: true

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Epson WF-2530
    hostname: epson-wf-2530
    priority: 1
    mac: b0:e8:92:58:9d:63
    ip: 192.168.1.99
    dhcp: true

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Loungeroom TV
    hostname: media-loungeroom-tv
    priority: 1
    mac: 54:3a:d6:55:37:50
    ip: 192.168.1.30
    dhcp: true

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Bedroom Apple TV
    hostname: media-kiels-tv
    priority: 1
    mac: 18:ee:69:17:6a:8f
    ip: 192.168.1.31
    dhcp: true

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: All media
    hostname: namic-eth0
    priority: 1
    mac: 68:64:4b:0a:08:15
    ip: 192.168.1.10
    dhcp: false

  - download_speed: 100mbps
    upload_speed: 100mbps
    desc: Media Server
    hostname: workshop
    priority: 1
    mac: 4c:72:b9:f8:4e:42
    ip: 192.168.1.97
    dhcp: true
    
