--- 
# Config
gateway: 192.168.1.3
lan_subnets:
  - 192.168.1.0/24 
  - 192.168.2.0/24
masquerade:
  - 192.168.1.0/24
  - 192.168.2.0/24
device: enp2s0
# DHCP options
broadcast-address: 192.168.1.25
dhcp-subnet: 192.168.1.0
dhcp-netmask: 255.255.255.0
dhcp-range: 192.168.1.100:192.168.1.200 

--- 
# Queue groups

kiel:
  desc: Kiel's devices
  priority: 1
  download_speed: 1000mbit
  upload_speed: 10000mbit

  devices:
  - download_speed: 12mbit
    desc: Kiel's laptop WiFi
    hostname: kiels-laptop
    priority: 1
    upload_speed: 800kbit
    mac: b8:e8:56:33:8c:30
    ip: 192.168.1.6
    dhcp: true

  - download_speed: 12mbit
    desc: Kiel's laptop Wired
    hostname: kiels-laptop-wired
    priority: 1
    upload_speed: 800kbit
    mac: 00:e0:4c:36:90:41
    ip: 192.168.1.96
    dhcp: true

  - download_speed: 12mbit
    upload_speed: 700kbit
    desc: Kiel's phone2
    hostname: kiels-phone2
    priority: 1
    mac: a8:3e:0e:9c:49:e7
    ip: 192.168.1.4
    dhcp: true

  - download_speed: 12mbit
    upload_speed: 700kbit
    desc: Kiel's phone
    hostname: kiels-phone
    priority: 1
    mac: f8:a9:d0:4d:ab:63
    ip: 192.168.1.5
    dhcp: true

  - download_speed: 12mbit
    upload_speed: 700kbit
    desc: Garage laptop
    hostname: garage-laptop
    priority: 1
    mac: 00:26:5e:82:c5:21
    ip: 192.168.1.70
    dhcp: true

sarah:
  desc: Sarah's devices
  priority: 2
  download_speed: 1000mbit
  upload_speed: 1000mbit

  devices:
  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Sarah's phone2
    hostname: sarahs-phone2
    priority: 2
    mac: f8:a9:d0:4d:aa:e0
    ip: 192.168.1.50
    dhcp: true

#  - download_speed: 5mbit
#    upload_speed: 500kbit
#    desc: Sarah's phone
#    hostname: sarahs-phone
#    priority: 2
#    mac: a8:3e:0e:9c:49:68
#    ip: 192.168.1.53
#    dhcp: true

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Sarah's laptop
    hostname: sarahs-laptop
    priority: 2
    mac: 64:80:99:FB:56:44
    ip: 192.168.1.51
    dhcp: true
    
eliza:
  desc: Eliza's devices
  priority: 3
  download_speed: 1000mbit
  upload_speed: 1000mbit
  devices:
  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Eliza's iPad
    hostname: elizas-ipad
    priority: 3
    mac: 24:a0:74:1a:95:23
    ip: 192.168.1.41
    dhcp: true

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Eliza's Phone
    hostname: elizas-phone
    priority: 3
    #mac: 38:f8:89:ec:5a:06
    mac: 58:1F:AA:87:69:99
    ip: 192.168.1.42
    dhcp: true

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Eliza's tablet
    hostname: elizas-tablet
    priority: 3
    mac: 14:dd:a9:46:bf:e4
    ip: 192.168.1.40
    dhcp: true

evie:
  desc: Evie's devices
  priority: 3
  download_speed: 1000mbit
  upload_speed: 1000mbit

  devices:
  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Evie's laptop
    hostname: evies-laptop
    priority: 3
    mac: 58:fb:84:2c:14:88
    ip: 192.168.1.20
    dhcp: true
    block_nightly: true
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123

    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00


  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Evie's tablet
    hostname: evies-tablet
    priority: 3
    mac: 14:dd:a9:46:b7:80
    ip: 192.168.1.21
    dhcp: true
    block_nightly: true
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123

    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Evie's iPad
    hostname: evies-ipad
    priority: 3
    mac: 5c:f7:e6:20:35:8d
    ip: 192.168.1.23
    dhcp: true
    block_nightly: true
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00


  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Evie's phone
    hostname: evies-phone
    priority: 3
    mac: ec:1f:72:21:f3:50
    ip: 192.168.1.24
    dhcp: true
    block_nightly: true
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Kate's
    hostname: kates-phone
    priority: 3
    mac: 08:e6:89:03:19:45
    ip: 192.168.1.25
    dhcp: true
    ##block_nightly: false
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123

isac:
  desc: Isac's devices
  priority: 3
  download_speed: 1000mbit
  upload_speed: 1000mbit
  #blocked: false

# f8:a9:d0:4d:aa:e0 
  devices:

  - download_speed: 12mbit
    desc: Isac Watch
    hostname: isacs-watch
    priority: 1
    upload_speed: 800kbit
    mac: 18:00:db:22:6a:eb
    ip: 192.168.1.17
    dhcp: true

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Isac's Wii
    hostname: isacs-wii
    priority: 3
    mac: 00:19:fd:07:2d:4f
    ip: 192.168.1.17
    dhcp: true
    #block_nightly: false
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Isac's Desktop
    hostname: isacs-desktop
    priority: 3
    mac: 20:e7:17:00:cb:a9
    ip: 192.168.1.16
    dhcp: true
    #block_nightly: false
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

  - download_speed: 3mbit
    upload_speed: 200kbit
    desc: Isac's playstation
    hostname: isacs-playstation
    priority: 3
    mac: c0:38:96:ad:01:59
    ip: 192.168.1.8
    dhcp: true
    #block_nightly: false
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00
    
  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Isac's iPad
    hostname: isacs-ipad
    priority: 3
    mac: 24:a2:e1:04:53:f4
    ip: 192.168.1.12
    dhcp: true
    #block_nightly: false
    block_time: 22:00
    unblock_time: 6:00
#    domain-name-servers: 
#      - 208.67.222.123
#      - 208.67.220.123
    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Isac's iPhone
    hostname: isacs-phone
    priority: 3
    # Oppa
    #mac: d4:1a:3f:e6:82:c1
    # Loan phone
    #mac: 08:ec:a9:12:7e:7f
    #nexus 5
    mac: a8:3e:0e:9c:49:68
    ip: 192.168.1.9
    dhcp: true
    #block_nightly: false
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Isac's computer
    hostname: isacs-computer
    priority: 3
    mac: 28:3a:4d:0f:c3:c3
    ip: 192.168.1.14
    dhcp: true
    #block_nightly: false
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

  - download_speed: 5mbit
    upload_speed: 500kbit
    desc: Isac's computer 2
    hostname: isacs-computer2
    priority: 3
    mac: 38:b1:db:90:73:89
    ip: 192.168.1.15
    dhcp: true
    #block_nightly: false
    block_time: 22:00
    unblock_time: 6:00
    domain-name-servers: 
      - 208.67.222.123
      - 208.67.220.123
    blocking:
      active: true
      schedule:
        monday: 
          unblock: 6:00
          block: 22:00
        tuesday: 
          unblock: 6:00
          block: 22:00
        wednesday: 
          unblock: 6:00
          block: 22:00
        thursday: 
          unblock: 6:00
          block: 22:00
        friday: 
          unblock: 6:00
        sunday:
          block: 22:00

linda:
  desc: Linda's devices
  priority: 3
  download_speed: 1000mbit
  upload_speed: 1000mbit

  devices:
  - download_speed: 3mbit
    desc: Linda's iPad
    hostname: lindas-ipad
    priority: 3
    upload_speed: 800kbit
    mac: b8:63:4d:cc:e8:1a
    ip: 192.168.1.60
    dhcp: true

  - download_speed: 3mbit
    desc: Linda's Phone
    hostname: lindas-phone
    priority: 3
    upload_speed: 800kbit
    mac: d8:c4:6a:cb:53:ca
    ip: 192.168.1.61
    dhcp: true

print:
  desc: Epson WF-2530
  priority: 1
  download_speed: 1000mbit
  upload_speed: 1000mbit

  devices:
  - download_speed: 6mbit
    upload_speed: 500kbit
    desc: Epson WF-2530
    hostname: epson-wf-2530
    priority: 1
    mac: b0:e8:92:58:9d:63
    ip: 192.168.1.99
    dhcp: true

camera:
  desc: Samsung
  priority: 1
  download_speed: 1000mbit
  upload_speed: 1000mbit

  devices:
  - download_speed: 12mbit
    upload_speed: 500kbit
    desc: Samsung
    hostname: camera
    priority: 1
    mac: a0:21:95:5c:2b:7e
    ip: 192.168.1.98
    dhcp: true




media:
  desc: Media devices
  priority: 1
  download_speed: 1000mbit
  upload_speed: 1000mbit

  devices:
  - download_speed: 6mbit
    upload_speed: 500kbit
    desc: Loungeroom Apple TV
    hostname: media-loungeroom-tv
    priority: 1
    mac: 68:64:4b:0a:08:15
    ip: 192.168.1.30
    dhcp: true

  - download_speed: 6mbit
    upload_speed: 500kbit
    desc: Bedroom Apple TV
    hostname: media-kiels-tv
    priority: 1
    mac: 18:ee:69:17:6a:8f
    ip: 192.168.1.31
    dhcp: true

  - download_speed: 1000mbit
    upload_speed: 500kbit
    desc: All media
    hostname: namic-eth0
    priority: 1
    mac: 68:64:4b:0a:08:15
    ip: 192.168.1.10
    dhcp: false
